In [ ]:
!pip install numpy

In [1]:
import numpy as np
import pandas as pd

## 2D Array (Jan 25)

In [ ]:
arr = np.arange(0,13)
arr

In [ ]:
arr[ : : -1] # -1 = backward

In [ ]:
arr[0:0] # [0:0] not inclusive (everything on the left) --> empty

In [ ]:
arr[4:7]

In [ ]:
revarr = np.array([28, 8 , 10, 6, 3])
revarr

In [ ]:
revarr[: : -1]

In [ ]:
arr2 = np.arange(1,13)
arr2

In [ ]:
arr2.shape # output (12,0) = 12 rows, 0 column

In [ ]:
arr2 = arr2.reshape(3,4) # --> 3 rows, 4 columns 
arr2

In [ ]:
arr2.reshape(1,12) # 1 row, 12 columns

In [ ]:
np.array([(1,2,3,4),(1,2,3,4),(9,10,11,12)]) # set in list in array

In [ ]:
arr2[ : , : ]

In [ ]:
arr2[0:2, 2:3].ravel() # 1:2 = row location, 2:3 = number location, ravel() = 1D array

In [ ]:
vf = arr2[0:2, 2:3].flat # output is an object
vf

In [ ]:
list(vf)

In [ ]:
np.array(vf)

In [ ]:
arr2[:,:]

In [ ]:
arr2[0:1, :]

In [ ]:
arr2[2:3, :]

In [ ]:
arr2[0:1, :] + arr2[2:3, :]

In [ ]:
arr2[0:1, :] ** arr2[2:3, :]

In [ ]:
arr2[0:1, :] / arr2[2:3, :]

In [ ]:
arr2[0:1, :].ravel() ** arr2[2:3, :].ravel()

In [ ]:
arr2[[0,2], 2:3].ravel()

## A.Numpy Array (Jan 24)

In [ ]:
arr = np.array([1,2,3,4])
arr

In [ ]:
arr.dtype

In [ ]:
arr = arr.astype('int64') # reassign arr
arr.dtype

In [ ]:
type(arr)


In [ ]:
np.append(arr, 28.0) #reassign float type

In [ ]:
arr 

In [ ]:
np.append(arr, '28.0')

In [ ]:
arr = np.append(arr, [5,6,7,8])

In [ ]:
arr= arr.reshape(2,4)

In [ ]:
arr[0][1]

In [ ]:
arr[0:2][-1]

In [ ]:
# pd.Series({'first': arr[0], 'second': arr[1]})

In [ ]:
df = pd.DataFrame({'first': arr[0], 'second': arr[1]})
df

In [ ]:
df.loc[2, ['first', 'second']]

In [ ]:
type(df['first'])

In [ ]:
arr2 = np.arrange(1,6)
arr2

In [ ]:
# random() --> print value between 0 and 1

In [ ]:
l = [2,4,6,8]

In [ ]:
l.append('Pat')

In [ ]:
for i in l:
    print (type(l))

# 1. Create

In [2]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [3]:
data

array([[[0.10488127, 0.12697471, 0.90872709, 0.03882601],
        [0.01042594, 0.30919909, 0.64777742, 0.26863868],
        [0.70163297, 0.59268521, 0.13312229, 0.40924614]],

       [[0.71793476, 0.04643933, 0.86724207, 0.1170708 ],
        [0.26469679, 0.68090097, 0.59859743, 0.1087082 ],
        [0.81877751, 0.46936739, 0.06924948, 0.38670945]]])

In [4]:
data[1: , 1: , 2: ]  

array([[[0.59859743, 0.1087082 ],
        [0.06924948, 0.38670945]]])

In [5]:
np.std(data)

0.290328915142571

In [6]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [9]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [10]:
type(arr)

numpy.ndarray

In [13]:
arr = np.array([1,2,3,4]*2).reshape(2,4)
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [14]:
np.random.seed(42)
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [15]:
list2

array([0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914])

# 2. Read

In [ ]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [ ]:
types

In [ ]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [ ]:
singleval

In [ ]:
data

# 3. Update

In [ ]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [ ]:
list2

In [ ]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [ ]:
dot

In [ ]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [ ]:
maxs

In [ ]:
data

In [ ]:
data[0][0][0] = 700

In [ ]:
data

In [ ]:
data.sort()
data

In [ ]:
print(data.shape)

In [ ]:
data = data.reshape((2,2,-1))
data.shape

In [ ]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

In [ ]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

# 4. Delete

In [ ]:
data

In [ ]:
np.delete(data, 0, axis=1)

In [ ]:
np.save("new array", data)

In [ ]:
test = np.load("new array.npy")

In [ ]:
test